import type { Metadata } from 'next';
import './globals.css';
import '../../dist/snes.min.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <>{children}</>
      </body>
    </html>
  );
}
